name: Human Services Link-[For Any City]
url: http://link.sf.adopta.agency/

author:
  name: 'Kin Lane'
  email: 'info@apievangelist.com'
markdown: kramdown

permalink: /:categories/:year/:month/:day/:title/
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]

get_color: 009900;
post_color: 0000ff;
put_color: FF0080;
delete_color: FF9900;

github_org: adopta-agency
github_repo: link-sf
github_branch: master

# URL to the issues page for this
support_title: Support
support_description: If you need any help, have questions, or would like to get involved, please use the following links.
support_email: info@apievangelist.com
support_twitter: apievangelist

# Login area
login:
signup:

# blog stuff
permalink: /:categories/:year/:month/:day/:title/
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", ".DS_Store"]

paginate: 150
paginate_path: "/blog/page:num"

status_key: ASzjKOjFKPYC0D-RBGPWtw
status_id: 1572918
